### PR TITLE
add updated wheels for client and sdk deps

### PR DESCRIPTION
**Pull request by creviera**
# Description

Adds wheels for client and sdk as specified in their requirements.in files

# Test Plan

- [ ] add a diff review for each dependency updated, see https://github.com/freedomofpress/securedrop-debian-packaging/wiki/PyYAML-5.3.1-to-5.4.1 for example

### CODE REVIEW

**Comment by creviera** [comment]
TODO:
- [ ] @conorsch will need to sign sha256sums.txt

**Comment by creviera** [comment]
I believe CI is failing until we get a signature, but open for discussion is whether or not we want to update the MarkupSafe dependency at this point or if we want to keep pinning to 1.1.1 (see https://github.com/freedomofpress/securedrop-client/pull/1274/commits/3e214ac1923e768f2d7446396d983ff4d39304c4#r682211916).

**Comment by kushaldas** [comment]
All diff-reviews:

- https://github.com/freedomofpress/securedrop-debian-packaging/wiki/Certify-2018.10.15-to-2021.5.30
- https://github.com/freedomofpress/securedrop-debian-packaging/wiki/Markupsafe-1.1.1-to-2.0.1
- https://github.com/freedomofpress/securedrop-debian-packaging/wiki/idna-2.7-to-2.8

**Review by kushaldas — APPROVED** [review]
Added all diff-reviews. rest of the change looks good. Approved.

**Pull request merged**
