### PR TITLE
Update securedrop-workstation-grsec for 5.15.41/bullseye

### PR DESCRIPTION
**Pull request by creviera**
Towards https://github.com/freedomofpress/securedrop-debian-packaging/issues/321

* Change the versioning scheme to `$KERNEL-$REVISION~$PLATFORM`. This means the package's "upstream version" will be the kernel version, so we can use variables like `${source:Upstream-Version}` and `$DEB_VERSION_UPSTREAM` to substitute in the kernel version without hardcoding it.
* Skip u2mfn code on bullseye, it's not needed anymore on Qubes 4.1.
* "Hack" CI to use `changelog-bullseye` since we need a different version on bullseye.

## Test plan
* [ ] Build on both buster and bullseye. Use `apt show securedrop-workstation-grsec_4.14.241-2~buster_amd64.deb` and `apt show securedrop-workstation-grsec_5.15.41-1~bullseye_amd64.deb` to verify the dependencies have the correct version substituted in
* [ ] Extract the control metdata with `ar x securedrop-workstation-grsec_5.15.41-1~bullseye_amd64.deb && tar xvf control.tar.xz`, and look at the postinst to verify the token was substituted properly.

### CODE REVIEW

**Comment by legoktm** [comment]
I think we still need some of the stuff Conor did in #301, let me take a stab at making it build on bullseye and buster...

**Comment by creviera** [comment]
I'm going to rebuild the kernel anyway before creating a PR with the new debs for dev-lfs. I'll link to that PR once it's ready.

**Comment by legoktm** [comment]
The CI logic is a bit busted still, I'll fix that up tomorrow. But the package should build as we want it on both bullseye and buster.

**Comment by legoktm** [comment]
CI correctly built `securedrop-workstation-grsec_5.15.38-1~bullseye_amd64.deb` and `securedrop-workstation-grsec_4.14.241-2~buster_amd64.deb` \o/

**Comment by legoktm** [comment]
The `${source:Upstream-Version}` syntax is documented at https://manpages.debian.org/bullseye/dpkg-dev/deb-substvars.5.en.html#source:Upstream

Tokens in postinst are documented at https://manpages.debian.org/bullseye/debhelper/dh_installdeb.1.en.html except the custom `--define` parameter is bullseye only, so we need to use sed for buster compat.

**Comment by creviera** [comment]
@legoktm It looks like `PKG_VERSION=5.15.41 PKG_PLATFORM=bullseye make securedrop-workstation-grsec` is failing now (it worked when I tested against these changes: https://github.com/freedomofpress/securedrop-debian-packaging/pull/301/files)... it looks like it has to do with the use of substitution variables maybe... I'll attach the error output from qubes in a followup comment

**Comment by legoktm** [comment]
Should be fixed with f5d13b3467760d214e74c2ee23924b824e87ad17.

**Comment by creviera** [comment]
Only thing left is to make sure we can run `scripts/update-changelog` so that it automatically formats the debian package version string appropriately for grsec as done manually in https://github.com/freedomofpress/securedrop-debian-packaging/pull/326/commits/f5d13b3467760d214e74c2ee23924b824e87ad17.

**Review by creviera — COMMENTED** [review]
Just tested the recent changes for a new test version of grsec and another package (i chose proxy) for a regression check. 

So this lgtm and will need your approval still @legoktm!

**Review by legoktm — APPROVED** [review]

**Pull request merged**
