### PR TITLE
Update `securedrop-workstation-config` for bullseye, refrain from building buster nightlies

### LINKED ISSUE #348: `securedrop-workstation-config`: Update mimeapps.list files for bullseye
`securedrop-workstation` tests for the sd-viewer DispVM template are failing at the moment on 4.1. On bullseye `eog.desktop` does not exist and neither `xdg-open example.jpg` nor `xdg-mime query default image/jpeg` work as expected because the desktop file for Eye of GNOME has been renamed to `org.gnome.eog.desktop`.

Hence: mentions of `eog.desktop` ought to be updated for bullseye.

### PR DESCRIPTION
**Pull request by eaon**
`eog.desktop` was renamed to `org.gnome.eog.desktop` on bullseye.
Updating this is necessary for the client to be able to successfully
open images.

Because the files we want to ship for buster and bullseye now diverge,
and because `securedrop-workstation-config` is unlikely to see a new
release on buster, we want to refrain from building this package on
nightlies, otherwise `securedrop-workstation` tests in dom0 would start
failing on 4.0

Fixes #348

## Testing

On Qubes OS R4.1:

- [ ] (Pre-check) Start a terminal for `sd-viewer`, and run `xdg-mime query default image/jpeg` - it should return `open-in-dvm.desktop`
- [ ] Build `securedrop-workstation-config` manually, transfer it to `sd-large-bullseye-template` and install it with `dpkg -i`
- [ ] Restart `sd-viewer` to make sure it uses the updated package
- [ ] Start a terminal for `sd-viewer`, and run `xdg-mime query default image/jpeg` - it should return `org.gnome.eog.desktop`

### CODE REVIEW

**Review by cfm — APPROVED** [review]
Test plan checks out on Qubes 4.1!  Approving conditionally on passing CI, where `reprotest-wheels` is currently stalling out in installing `python-dateutil` for `securedrop-client`.

- [x] (Pre-check) Start a terminal for `sd-viewer`, and run `xdg-mime query default image/jpeg` - it should return `open-in-dvm.desktop`
- [x] Build `securedrop-workstation-config` manually, transfer it to `sd-large-bullseye-template` and install it with `dpkg -i`

```sh-session
[cfm@dom0 ~]$ qvm-tags sd-large-bullseye-template del sd-workstation

user@sd-dev:~/securedrop-debian-packaging$ qvm-copy  # to sd-large-bullseye-template

[cfm@dom0 ~]$ qvm-tags sd-large-bullseye-template add sd-workstation
```

- [x] Restart `sd-viewer` to make sure it uses the updated package
- [x] Start a terminal for `sd-viewer`, and run `xdg-mime query default image/jpeg` - it should return `org.gnome.eog.desktop`

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop-debian-packaging/pull/349#pullrequestreview-1016133706>:

> Approving conditionally on passing CI, where `reprotest-wheels` is currently stalling out in installing `python-dateutil` for `securedrop-client`.

Rerunning `reprotest-wheels` from last night's `nightlies` on `main`, where it passed, now stalls out too, in the same place and in the same way.  So it's something upstream, unrelated to this pull request, that I'll hope clears up overnight.

**Comment by creviera** [comment]
> @creviera, are we okay to merge this pull request as is and open a ticket to investigate this reprotest-wheels failure separately?

@cfm - agreed that this looks unrelated, so capturing it in an issue and merging makes sense to me!

**Comment by cfm** [comment]
Thanks, @creviera!  Merging; ticket to follow.

**Pull request merged**
