### PR TITLE
Rework packaging scripts to remove pipenv

### LINKED ISSUE #42: Remove pipenv in favor of pip-tools
See detailed rationale in original issue on the client side here: https://github.com/freedomofpress/securedrop-client/issues/370

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #42. I've tried to be pretty verbose here in comments in the diff for maintenance sake. 

One can test these changes by going through the full packaging workflow with the following two pending PRs: 

- https://github.com/freedomofpress/securedrop-proxy/pull/33 (with commit f946fe38f4dc0b4b71cff3ea8d318fcca1599c09 dropped which fixes the CVEs in the dependencies in that repo (alternatively one can add those packages to FPF's PyPI after review))
- https://github.com/freedomofpress/securedrop-client/pull/372 (with commit 97cdd30117aa0e4dff331d586376a8da6e0eb9f4 dropped which fixes the CVEs in the dependencies in that repo (alternatively one can add those packages to FPF's PyPI after review))

Note: this PR is ready for review and will be taken off of draft mode once this and the above two PRs are approved - this is such that we can merge all three in a coordinated manner without breaking debian package builds

(CI is "failing" because I enabled circle CI here to add CI jobs in #44 but there's no config file in the master branch/this PR, so we should ignore until we merge #44)

### CODE REVIEW

**Comment by kushaldas** [comment]
I tried the above against `bye-pipenv` branch of `securedrop-client` repo.

**Comment by redshiftzero** [comment]
Thanks for running through this. That requirements.txt state could happen previously if `make requirements` failed for some reason, e.g. a dependency was absent from FPF's PyPI mirror. I've added two commits which:

- Won't modify the input requirements file unless `update-requirements` succeeds
- Removes `create-requirements` and just does all the relevant logic in one place in Python in `update-requirements` to simplify a bit

Let me know what you think! This _should_ do the trick.

**Comment by kushaldas** [comment]
I will push the change of the `requirements.txt` file name to this PR.

**Comment by redshiftzero** [comment]
I've taken all three PRs out of draft mode for merge:

https://github.com/freedomofpress/securedrop-debian-packaging/pull/43 (this PR)
https://github.com/freedomofpress/securedrop-client/pull/372
https://github.com/freedomofpress/securedrop-proxy/pull/33

**Pull request merged**
