### PR TITLE
adds Babel to build requirements

### PR DESCRIPTION
**Pull request by cfm**
For freedomofpress/securedrop-client#1294 towards freedomofpress/securedrop-client#1283:

1. adds [Babel 2.9.1](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/Babel-2.5.1-to-2.9.1) to build requirements; and
2. brazenly signs the resulting checksums, even though I am not a maintainer, so that freedomofpress/securedrop-client@7959f3708409f3c649ffd3d6eedb920c5d5a1a21 can use this branch in testing.  :-)

**IMPORTANT.**  At a minimum, a maintainer will need to rebase out 1c12f4657247de2a27073bcfa394169749bafa39 and resign the checksums as usual:

```sh-session
$ # now let us sign the list of sha256sums
$ gpg --armor --output bootstrap-sha256sums.txt.asc --detach-sig  bootstrap-sha256sums.txt
$ # We can even verify if we want
$ BOOTSTRAP=true ./scripts/verify-sha256sum-signature
$ # Update the build-requirements.txt file
$ PKG_DIR=$PWD BOOTSTRAP=true ./scripts/update-requirements
```

## Test plan

In addition to the usual requirements for a maintainer to approve a new or updated dependency here:

1. [ ] CI passes here
2. [ ] CI passes for freedomofpress/securedrop-client@7959f3708409f3c649ffd3d6eedb920c5d5a1a21

### CODE REVIEW

**Review by creviera — COMMENTED** [review]
Review in progress... just double-checking with @kushaldas first about intentions around diff reviewing the more recent addition of the bootstrap deps

**Comment by kushaldas** [comment]
@creviera We should  do diff-review for any changes to bootstrap. Also the wheels should be rebuild  to verify and hash(s) should be matched against upstream.

**Comment by creviera** [comment]
This is currently blocked by https://github.com/freedomofpress/securedrop-debian-packaging/issues/274

**Review by kushaldas — APPROVED** [review]
The update is good.

- [x] CI is passing
- [x] There are diff-reviews 

Approved.

**Pull request merged**
