### PR TITLE
Remove buster, add failing bookworm jobs

### PR DESCRIPTION
**Pull request by legoktm**
**_Note, #372 must be merged before this one!_**

We'd like bookworm jobs to be able to fail, but when they do fail it
should make an appropriate level of noise so we can investigate why they
failed. But they should also not stop the bullseye packages from being
uploaded!

So we split the bookworm jobs into a separate track ("build2"), and have
separate push jobs for each version. The push-bullseye job goes before
the push-bookworm one in case bookworm jobs are failing.

Note that currently all the bookworm jobs are failing because of
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017046. I've put in a
fix for that, it should be in bookworm in the next 3-5 days.

Refs #369.

### CODE REVIEW

**Comment by legoktm** [comment]
Here's what the nightly job ordering looks like:

Screenshot 2022-08-25 at 16-33-45 Workflow - securedrop-debian-packaging_1915_755b16f0-d3b9-46d9-b17b-9aff4cc588bb`

**Comment by eloquence** [comment]
What should the policy on bookworm checks be? Should it be acceptable to merge PRs even if bookworm checks are failing?

If the answer is yes, just noting that, as I understand it, those commits will show up with a red "X" in the commit history, regardless of whether the check is required or not. Not sure if there's a good way around that.

**Comment by legoktm** [comment]
> What should the policy on bookworm checks be? Should it be acceptable to merge PRs even if bookworm checks are failing?

Yes. I think people should quickly check to see if their change is causing the failure, and if so fix it (or less preferred, log an issue).

> If the answer is yes, just noting that, as I understand it, those commits will show up with a red "X" in the commit history on GitHub, regardless of whether the check is required or not. Not sure if there's a good way around that.

Yeah :-(

**Comment by legoktm** [comment]
Remaining bookworm failures:
* securedrop-client: needs some wheels to be built
* securedrop-proxy: same
* securedrop-workstation-grsec: I didn't copy over the changelog, leaving intentionally broken since it's going to go away soon I hope.

**Comment by legoktm** [comment]
I'm going to leave removing the Python 3.7 wheels for another PR just so the resigning of the checksums file doesn't cause issues on rebase.

**Comment by eloquence** [comment]
> securedrop-client: needs some wheels to be built
> securedrop-proxy: same

Do you want to do that as part of this PR before merging?

**Comment by legoktm** [comment]
No strong preference on my end, I think if I get to it before this is reviewed/merged I can add it to this PR, otherwise it can go separately.

**Review by gonzalo-bulnes — COMMENTED** [review]
I'm realizing how unfamiliar I am with this repo :stuck_out_tongue_closed_eyes: so I'll only comment.

- The goal is clear to me :white_check_mark: 
- The limitations in what we can do are too :white_check_mark: 
- And with that in mind, the mechanics are clear too, with caveats that I think are acceptable (We'll be merging red builds somewhat regularly. Because it's a conscious decision I can live with that :P) :heavy_check_mark: 
- I'm not sure who signs the checksums file, so I haven't checked that. :tangerine: 
- I cannot spot any mistakes in the implementation. Take that with a grain of salt, but I also see that CI looks as expected, so I would go forward and ship it. :heavy_check_mark: 

I'll let you give your thoughts too @eloquence !

**Comment by legoktm** [comment]
> * I'm not sure who signs the checksums file, so I haven't checked that. :tangerine:

Anyone who has a key in the [`pubkeys/`](https://github.com/freedomofpress/securedrop-debian-packaging/tree/main/pubkeys) folder can resign the file.

**Review by cfm — CHANGES_REQUESTED** [review]
I love how this change shows off #371's parameterization of this CI workflow!

- [x] Prerequisite #372 is merged
- [x] CI is passing:
    - [x] bullseye
    - [x] bookworm, except for expected failures:
        - `securedrop-client` itself does not yet have a pinned hash for Python 3.10 wheels (pending freedomofpress/securedrop-client#1554)
        - `securedrop-proxy` itself does not yet have a pinned hash for Python 3.10 wheels (pending freedomofpress/securedrop-proxy#104)
        - `securedrop-workstation-grsec` does not (and [will not](https://github.com/freedomofpress/securedrop-debian-packaging/pull/373#issuecomment-1232609997)) have its own `changelog-bookworm`

In Monday's Workstation hangout we discussed https://github.com/freedomofpress/securedrop-debian-packaging/pull/373#issuecomment-1230693452 and agreed on a criterion for assessing provisional bookworm (and future Debian testing) builds (my summary notes):

> If it's your change that's causing the bookworm job to fail, you should fix it before merge.  If it's upstream, it's a judgment call.

As always, I would prefer to record this guidance to maintainers explicitly somewhere.  @legoktm, do you think could be done usefully in a pull-request template here? or will that be necessary per upstream component repository (`securedrop-client`, etc.)?

**Comment by legoktm** [comment]
> As always, I would prefer to record this guidance to maintainers explicitly somewhere. @legoktm, do you think could be done usefully in a pull-request template here? or will that be necessary per upstream component repository (`securedrop-client`, etc.)?

Yes to both, in that bookworm job failures might need to be ignored here as well as in component repositories. I note that we currently don't even have a pull request template here :<, and the README is already a mess of documentation. Since it's a general policy that will span multiple repos, maybe it belongs better in the new developer docs?

**Comment by eloquence** [comment]
My suggestion would be for a short paragraph into a PR template for now:

> == Checklist ==
> 
> [ ] I've verified that this PR does not introduce any new `bookworm` test failures

Or similar.

**Comment by legoktm** [comment]
OK, how's that?

**Review by cfm — APPROVED** [review]
fbceaa89aed2158d875b7b1b6f51e39b6a6d03d3 nicely captures the spirit of "bookworm or bust".  :-)  Thanks, @eloquence and @legoktm!  Approving and merging on the basis of <https://github.com/freedomofpress/securedrop-debian-packaging/pull/373#pullrequestreview-1094158230>.

**Comment by legoktm** [comment]
Wheee, thank you to all 3 reviewers :-)

**Pull request merged**
