### PR TITLE
add wheel for werkzeug 2.0.2

### PR DESCRIPTION
**Pull request by creviera**
# Description

Adds wheel and associated tarball for werkzeug 2.0.2 to improve security of debugger cookies, see https://github.com/pallets/werkzeug/issues/2156.

# Test Plan

- [x] Diff review for werkzeug https://github.com/freedomofpress/securedrop-debian-packaging/wiki/werkzeug-0.16.0-to-werkzeug-2.0.2

### CODE REVIEW

**Comment by creviera** [comment]
Looks like we are running into a reproducible deb issue, so taking a moment to investigate: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1343/workflows/1a0b16f4-d241-4057-8f34-33c99a1ce8e7/jobs/10448

**Comment by creviera** [comment]
## Notes for comparing reproducible packages
When I build packages locally I get:
* `0d15a0c60f2d8ac1813a0493db405231796fb282c6ab30ab1e7ec6e1b277577e securedrop-export_0.2.7dev0+buster_all.deb`
* `fc38fec74181189d07d28573d504c49485370aaabfaa3a4d227898341881b163 securedrop-proxy_0.3.2dev0+buster_all.deb`

**Comment by creviera** [comment]
looks like the issue is:
```
PKG_VERSION not set, inferring from recent releases...
Failed to infer version
make: *** [Makefile:5: securedrop-proxy] Error 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 831, in run
    return 0 if check_func(*check_args) else 1
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 363, in check
    local_dists = [proc.send(nv) for nv in zip(bnames, build_variations)]
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 363, in <listcomp>
    local_dists = [proc.send(nv) for nv in zip(bnames, build_variations)]
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 329, in corun_builds
    bctx.run_build(testbed, build, os.environ, artifact_pattern, testbed_build_pre, no_clean_on_error)
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 220, in run_build
    kind='build')
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 64, in check_exec2
    adtlog.AutopkgtestError)
  File "/usr/lib/python3/dist-packages/reprotest/__init__.py", line 70, in bomb
    raise _type(m)
reprotest.lib.adtlog.AutopkgtestError: "sh -ec run_build() {
    mkdir -p /tmp/reprotest.p0VvwL/build-control-aux && \
    mv /tmp/reprotest.p0VvwL/build-control/ /tmp/reprotest.p0VvwL/const_build_path && \
    SETARCH_ARCH=$(uname -m) && \
    SETARCH_OPTS="$SETARCH_OPTS -R" && \
    CPU_MAX=$(nproc) && \
    CPU_MIN=$({ echo $CPU_MAX; echo 1; } | sort -n | head -n1) && \
    CPU_NUM=$CPU_MIN && \
    umask 0022 && \
    export REPROTEST_BUILD_PATH=/tmp/reprotest.p0VvwL/const_build_path/ && \
    export REPROTEST_UMASK=$(umask) && \
    faketime @1635792985 \
    taskset -a -c $(echo $(shuf -i0-$((CPU_MAX - 1)) -n$CPU_NUM) | tr ' ' ,) \
     \
    sh -ec 'cd "$REPROTEST_BUILD_PATH"; unset REPROTEST_BUILD_PATH; umask "$REPROTEST_UMASK"; unset REPROTEST_UMASK; make securedrop-proxy'
}
```

**Comment by creviera** [comment]
looks like i don't have access to the [quay image used in CI](https://github.com/freedomofpress/securedrop-debian-packaging/blob/c4f7822945b4965f93187ca5e1bb535b82f5162b/.circleci/config.yml#L251) which I would download to try to repro the issue, so tabling this for now (I mentioned my access issue to infra and @conorsch has offered to take a look into resolving this blocker, which is not the most pressing issue right now)

**Comment by conorsch** [comment]
@creviera see https://github.com/freedomofpress/securedrop-debian-packaging/pull/278, which should cure what ails CI here.

**Comment by creviera** [comment]
woohoo, your fix worked, @conorsch -- this is ready for final review

**Review by conorsch — APPROVED** [review]

**Pull request merged**
